apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nokiy-cms-secrets
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: nokiy-cms-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        nokiy.config.toml: |
          [log]
          level = "info"

          [api]
          url = "http://localhost:8080"

          [postgres]
          uri = "postgres://{{ .username }}:{{ .password }}@postgres-rw:5432/documents"

          [redis]
          uri = "redis://redis:6379/0"

          [cache]
          type = "fs"
          root = "/cache"
          max_size = 5368709120 # 5 GiB
          ttl = 2592000 # 30 days

          [archive]
          type = "b2"
          root = "archive"
          application_key_id = "{{ .B2_KEY_ID }}"
          application_key = "{{ .B2_APPLICATION_KEY }}"
          bucket_id = "{{ .B2_BUCKET_ID }}"
          bucket = "{{ .B2_BUCKET }}"
  data:
    - secretKey: username
      remoteRef:
        key: postgres-nokiy-documents
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-nokiy-documents
        property: password
    - secretKey: B2_KEY_ID
      remoteRef:
        key: nokiy-cms
        property: ACCESS_KEY
    - secretKey: B2_APPLICATION_KEY
      remoteRef:
        key: nokiy-cms
        property: SECRET_KEY
    - secretKey: B2_BUCKET_ID
      remoteRef:
        key: nokiy-cms
        property: BUCKET_ID
    - secretKey: B2_BUCKET
      remoteRef:
        key: nokiy-cms
        property: BUCKET
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nokiy-cms
  labels:
    app: nokiy-cms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nokiy-cms
  template:
    metadata:
      labels:
        app: nokiy-cms
    spec:
      containers:
      - name: nokiy-cms
        image: git.nokiy.net/reonokiy/nokiy:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        args: ["server", "start"]
        volumeMounts:
        - name: config
          mountPath: /app/nokiy.config.toml
          subPath: nokiy.config.toml
          readOnly: true
        - name: cache
          mountPath: /cache
      volumes:
      - name: config
        secret:
          secretName: nokiy-cms-secrets
      - name: cache
        emptyDir:
          sizeLimit: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nokiy-cms
spec:
  selector:
    app: nokiy-cms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nokiy-cms-internal-tls
spec:
  secretName: nokiy-cms-internal-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - cms.i.nokiy.net
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nokiy-cms-http
spec:
  entryPoints:
    - webinternal
  routes:
    - match: Host(`cms.i.nokiy.net`)
      kind: Rule
      middlewares:
        - name: internal-redirect-https
          namespace: traefik
        - name: compress
          namespace: traefik
      services:
        - name: nokiy-cms
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nokiy-cms
spec:
  entryPoints:
    - websecureinternal
  routes:
    - match: Host(`cms.i.nokiy.net`)
      kind: Rule
      middlewares:
        - name: compress
          namespace: traefik
      services:
        - name: nokiy-cms
          port: 80
  tls:
    secretName: nokiy-cms-internal-tls
