apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-nokiy-documents
  namespace: nokiy
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-nokiy-documents
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
  - secretKey: username
    remoteRef:
      key: postgres-nokiy-documents
      property: username
  - secretKey: password
    remoteRef:
      key: postgres-nokiy-documents
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-nokiy-auth
  namespace: nokiy
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-nokiy-auth
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
  - secretKey: username
    remoteRef:
      key: postgres-nokiy-auth
      property: username
  - secretKey: password
    remoteRef:
      key: postgres-nokiy-auth
      property: password
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: nokiy
spec:
  instances: 2
  enableSuperuserAccess: true
  storage:
    size: 1Gi
    storageClass: local-path
  managed:
    roles:
    - name: nokiy-documents
      ensure: present
      login: true
      superuser: false
      passwordSecret:
        name: postgres-nokiy-documents
    - name: nokiy-auth
      ensure: present
      login: true
      superuser: false
      passwordSecret:
        name: postgres-nokiy-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nokiy-documents
  namespace: nokiy
spec:
  name: documents
  owner: nokiy-documents
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nokiy-auth
  namespace: nokiy
spec:
  name: auth
  owner: nokiy-auth
  cluster:
    name: postgres
