apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-secrets.yaml
- external-dns.yaml
- local-path-provisioner.yaml
- csi-s3.yaml
- traefik.yaml
- cert-manager.yaml
- tailscale.yaml
- cnpg.yaml
# - redis-operator.yaml
- valkey-operator.yaml
# - k8s-monitoring.yaml
- tailscale-traefik.yaml
- kube-vip.yaml
- elastic.yaml
