apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-secrets.yaml
- external-dns.yaml
- cert-manager.yaml
- tailscale.yaml
- cnpg.yaml
- openebs.yaml
- redis-operator.yaml
- k8s-monitoring.yaml
