apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mastodon.yaml
# - elasticsearch.yaml
- redis.yaml

labels:
- pairs:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/instance: mastodon
