apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 12h
  url: https://mastodon.github.io/helm-charts
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-secrets
  namespace: mastodon
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: mastodon-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
  data:
  - secretKey: secret-key-base
    remoteRef:
      key: mastodon
      property: SECRET_KEY_BASE
  - secretKey: vapid-private-key
    remoteRef:
      key: mastodon
      property: VAPID_PRIVATE_KEY
  - secretKey: vapid-public-key
    remoteRef:
      key: mastodon
      property: VAPID_PUBLIC_KEY
  - secretKey: are-primary-key
    remoteRef:
      key: mastodon
      property: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
  - secretKey: are-deterministic-key
    remoteRef:
      key: mastodon
      property: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
  - secretKey: are-derivation-salt
    remoteRef:
      key: mastodon
      property: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
  - secretKey: s3-access-key-id
    remoteRef:
      key: mastodon
      property: B2_ACCESS_KEY
  - secretKey: s3-secret-access-key
    remoteRef:
      key: mastodon
      property: B2_SECRET_KEY
  - secretKey: smtp-username
    remoteRef:
      key: mastodon
      property: SMTP_USERNAME
  - secretKey: smtp-password
    remoteRef:
      key: mastodon
      property: SMTP_PASSWORD
  - secretKey: postgres-username
    remoteRef:
      key: mastodon
      property: POSTGRES_USERNAME
  - secretKey: postgres-password
    remoteRef:
      key: mastodon
      property: POSTGRES_PASSWORD
  - secretKey: redis-password
    remoteRef:
      key: mastodon
      property: REDIS_PASSWORD
  - secretKey: oidc-client-secret
    remoteRef:
      key: mastodon
      property: OIDC_CLIENT_SECRET
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  interval: 1h
  chart:
    spec:
      chart: mastodon
      version: "0.2.7"
      sourceRef:
        kind: HelmRepository
        name: mastodon
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mastodon:
      localDomain: yi0.org
      webDomain: yi0.org
      trustedProxyIp: "10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16"
      authorizedFetch: true
      secrets:
        existingSecret: mastodon-secrets
        existingSecretKeys:
          secretKeyBase: secret-key-base
          vapidPrivateKey: vapid-private-key
          vapidPublicKey: vapid-public-key
          arePrimaryKey: are-primary-key
          areDeterministicKey: are-deterministic-key
          areKeyDerivationSalt: are-derivation-salt
      s3:
        endpoint: s3.us-east-005.backblazeb2.com
        hostname: s3.us-east-005.backblazeb2.com
        region: us-east-005
        bucket: mastodon-yi0-org
        protocol: https
        existingSecret: mastodon-secrets
        existingSecretKeys:
          accessKeyId: s3-access-key-id
          secretAccessKey: s3-secret-access-key
      smtp:
        server: email-smtp.ap-southeast-1.amazonaws.com
        port: 587
        domain: mail.yi0.org
        fromAddress: noreply@mail.yi0.org
        existingSecret: mastodon-secrets
        existingSecretKeys:
          username: smtp-username
          password: smtp-password
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: yi0.org
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
      - host: yi0.org
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: mastodon-tls
        hosts:
        - yi0.org
    postgresql:
      hostname: pooler-rw.postgres.svc.cluster.local
      port: 5432
      database: mastodon
      existingSecret: mastodon-secrets
      existingSecretKeys:
        username: postgres-username
        password: postgres-password
      direct:
        hostname: postgres-rw.postgres.svc.cluster.local
        port: 5432
        database: mastodon
    redis:
      hostname: valkey-mastodon.mastodon.svc.cluster.local
      port: 6379
      existingSecret: mastodon-secrets
      existingSecretKeys:
        password: redis-password
    externalAuth:
      oidc:
        enabled: true
        displayName: "NOKIY ID"
        issuer: https://id.nokiy.net/
        discovery: true
        scope: "openid,profile,email"
        uidField: preferred_username
        clientId: mastodon
        # clientSecret: SECRETKEY
        redirectUri: https://yi0.org/auth/auth/openid_connect/callback
        assumeEmailIsVerified: true
  valuesFrom:
    - kind: Secret
      name: mastodon-secrets
      valuesKey: oidc-client-secret
      targetPath: externalAuth.oidc.clientSecret
