---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-init
  namespace: flux-system
spec:
  interval: 5m
  path: ./common/authentik/init
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-database
  namespace: flux-system
spec:
  interval: 5m
  path: ./common/authentik/database-shared
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: authentik-init
    - name: cnpg
    - name: redis-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./common/authentik/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: authentik-init
    - name: external-secrets-release
    - name: external-secrets-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-release
  namespace: flux-system
spec:
  interval: 5m
  path: ./common/authentik/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: authentik-database
    - name: authentik-secrets
    - name: traefik
    - name: cert-manager-letsencrypt
    - name: redis-operator
    - name: external-dns-release
  patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: authentik
        namespace: authentik
      spec:
        values:
          authentik:
            postgresql:
              host: postgres-rw.postgres.svc.cluster.local
          server:
            ingress:
              annotations:
                external-dns.alpha.kubernetes.io/hostname: auth.nokiy.net
                external-dns.alpha.kubernetes.io/ttl: "300"
    target:
      kind: HelmRelease
      name: authentik
      namespace: authentik
