apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - authentik.yaml # archived
- arpk.yaml
- cinny.yaml
- forgejo.yaml
- gotosocial.yaml
- linkding.yaml
- mastodon.yaml
- miniflux.yaml
- mlflow.yaml
- nokiy.yaml
- notion-sync.yaml
- pocket-id.yaml
- rsshub.yaml
- synapse.yaml
- tg-bot.yaml
- tsync.yaml
- unspeech.yaml
