---
apiVersion: v1
kind: Namespace
metadata:
  name: nokiy
  labels:
    nokiy.net/cluster-secret-store: "production"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: notion2md-server
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/reonokiy/notion2md-server.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notion2md
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: notion2md-server
  targetNamespace: nokiy
  timeout: 2m
  wait: true
  patches:
    - target:
        kind: Ingress
        name: notion2md-server
      patch: |-
        - op: add
          path: /spec/ingressClassName
          value: traefik
        - op: replace
          path: /spec/rules/0/host
          value: notion.nokiy.net
        - op: replace
          path: /spec/tls/0/hosts/0
          value: notion.nokiy.net
        - op: add
          path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
          value: notion.nokiy.net
        - op: add
          path: /metadata/annotations/external-dns.alpha.kubernetes.io~1ttl
          value: "300"
        - op: add
          path: /metadata/annotations/cert-manager.io~1cluster-issuer
          value: letsencrypt-prod
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nokiy-net
  namespace: flux-system
spec:
  interval: 10m
  url: https://git.nokiy.net/reonokiy/nokiy.net.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nokiy-net
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: nokiy-net
  targetNamespace: nokiy
  timeout: 2m
  wait: true
