apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synapse-postgres
  namespace: synapse
spec:
  instances: 2
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: postgres
      encoding: UTF-8
      localeCollate: C
      localeCType: C
  managed:
    roles:
      - name: synapse
        ensure: present
        login: true
        passwordSecret:
          name: synapse-postgres-credentials
      - name: mas
        ensure: present
        login: true
        passwordSecret:
          name: mas-postgres-credentials
  monitoring:
    enablePodMonitor: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: synapse-db
  namespace: synapse
spec:
  name: synapse
  owner: synapse
  cluster:
    name: synapse-postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mas-db
  namespace: synapse
spec:
  name: mas
  owner: mas
  cluster:
    name: synapse-postgres
