---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-monitoring-values
  namespace: k8s-monitoring
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: k8s-monitoring-values
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        values.yaml: |
          {{- $token := .token }}
          {{- $cluster := "${CLUSTER_NAME}" }}
          cluster:
            name: {{ $cluster }}
          destinations:
            - name: grafana-cloud-metrics
              type: prometheus
              url: https://prometheus-prod-49-prod-ap-northeast-0.grafana.net./api/prom/push
              auth:
                type: basic
                username: "1852962"
                password: {{ $token }}
            - name: grafana-cloud-logs
              type: loki
              url: https://logs-prod-030.grafana.net./loki/api/v1/push
              auth:
                type: basic
                username: "1025766"
                password: {{ $token }}
            - name: gc-otlp-endpoint
              type: otlp
              url: https://otlp-gateway-prod-ap-northeast-0.grafana.net./otlp
              protocol: http
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
              metrics:
                enabled: true
              logs:
                enabled: true
              traces:
                enabled: true
            - name: grafana-cloud-profiles
              type: pyroscope
              url: https://profiles-prod-019.grafana.net.:443
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
          clusterMetrics:
            enabled: true
            opencost:
              enabled: false
            kepler:
              enabled: true
          annotationAutodiscovery:
            enabled: true
          prometheusOperatorObjects:
            enabled: true
          clusterEvents:
            enabled: true
          nodeLogs:
            enabled: true
          podLogs:
            enabled: true
          applicationObservability:
            enabled: true
            receivers:
              otlp:
                grpc:
                  enabled: true
                  port: 4317
                http:
                  enabled: true
                  port: 4318
              zipkin:
                enabled: true
                port: 9411
          autoInstrumentation:
            enabled: true
          profiling:
            enabled: true
          alloy-metrics:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  value: {{ $token }}
                - name: CLUSTER_NAME
                  value: {{ $cluster }}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-019.grafana.net
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
          alloy-singleton:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  value: {{ $token }}
                - name: CLUSTER_NAME
                  value: {{ $cluster }}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-019.grafana.net
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
          alloy-logs:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  value: {{ $token }}
                - name: CLUSTER_NAME
                  value: {{ $cluster }}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-019.grafana.net
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
          alloy-receiver:
            enabled: true
            alloy:
              extraPorts:
                - name: otlp-grpc
                  port: 4317
                  targetPort: 4317
                  protocol: TCP
                - name: otlp-http
                  port: 4318
                  targetPort: 4318
                  protocol: TCP
                - name: zipkin
                  port: 9411
                  targetPort: 9411
                  protocol: TCP
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  value: {{ $token }}
                - name: CLUSTER_NAME
                  value: {{ $cluster }}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-019.grafana.net
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
          alloy-profiles:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  value: {{ $token }}
                - name: CLUSTER_NAME
                  value: {{ $cluster }}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-profiles-$(NODE_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-019.grafana.net
              auth:
                type: basic
                username: "1067987"
                password: {{ $token }}
  data:
    - secretKey: token
      remoteRef:
        key: k8s-monitoring
        property: PASSWORD
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: k8s-monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: k8s-monitoring
      version: "3.6.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-monitoring
        namespace: flux-system
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: k8s-monitoring-values
      valuesKey: values.yaml
