---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - init/namespace.yaml
  - release/deployment.yaml
  - config/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: header-echo
      app.kubernetes.io/instance: header-echo
