---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: forgejo-redis
  namespace: forgejo
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.4.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.79.0
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
