apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cinny.yaml
- forgejo.yaml
- linkding.yaml
- miniflux.yaml
- ntfy.yaml
- mlflow.yaml
- lakefs.yaml
- mastodon.yaml
- elastic.yaml
- moeru-ai.yaml
- phoenix.yaml
- rsshub.yaml
- sub2api.yaml
- synapse.yaml
- tg-bot.yaml
- tsync.yaml
- vm.yaml
- ni-svc.yaml
- omnigent.yaml
