apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cinny.yaml
- forgejo.yaml
- linkding.yaml
- miniflux.yaml
- mastodon.yaml
- elastic.yaml
- elasticsearch.yaml
- rsshub.yaml
- synapse.yaml
- tg-bot.yaml
- tsync.yaml
