---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- init
- secrets
- release
- config
labels:
- pairs:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/instance: forgejo
