apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: notion2md-server
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/reonokiy/notion2md-server.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notion2md
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: notion2md-server
  targetNamespace: nokiy
  timeout: 2m
  wait: true
  patches:
    - patch: |-
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: notion2md-server
          annotations:
            external-dns.alpha.kubernetes.io/hostname: notion.nokiy.net
            external-dns.alpha.kubernetes.io/ttl: "300"
            cert-manager.io/cluster-issuer: letsencrypt-prod
        spec:
          ingressClassName: traefik
          tls:
            - hosts:
                - notion.nokiy.net
              secretName: notion2md-tls
          rules:
            - host: notion.nokiy.net
      target:
        kind: Ingress
        name: notion2md-server
