---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: authentik
        property: SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: authentik
        property: POSTGRES_PASSWORD
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 12h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: "2025.10.2"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
  - kind: Secret
    name: authentik-secrets
    valuesKey: SECRET_KEY
    targetPath: authentik.secret_key
  - kind: Secret
    name: authentik-secrets
    valuesKey: POSTGRES_PASSWORD
    targetPath: authentik.postgresql.password
  values:
    authentik:
      error_reporting:
        enabled: true
      postgresql:
        host: pooler-rw.postgres.svc.cluster.local
        port: 5432
        name: authentik
        user: authentik
      redis:
        host: valkey-authentik.authentik.svc.cluster.local
        port: 6379

    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          external-dns.alpha.kubernetes.io/hostname: auth.nokiy.net
        hosts:
        - auth.nokiy.net
        tls:
        - secretName: authentik-tls
          hosts:
          - auth.nokiy.net

    postgresql:
      enabled: false

    redis:
      enabled: false
