---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: new-api
  namespace: new-api
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: new-api
      owner: new-api
  storage:
    size: 10Gi
    storageClass: local-path
