---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: new-api-secrets
  namespace: new-api
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: new-api-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        SESSION_SECRET: "{{ .session_secret | toString }}"
        CRYPTO_SECRET: "{{ .crypto_secret | toString }}"
  data:
    - secretKey: session_secret
      remoteRef:
        key: new-api
        property: SESSION_SECRET
    - secretKey: crypto_secret
      remoteRef:
        key: new-api
        property: CRYPTO_SECRET
