apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: b2-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
  data:
    - secretKey: access_key
      remoteRef:
        key: b2-backup
        property: ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: b2-backup
        property: SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-nokiy-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-nokiy-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: nokiy
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: nokiy
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-authentik-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-authentik-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: authentik
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-forgejo-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-forgejo-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: forgejo
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: forgejo
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-synapse-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-synapse-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: synapse
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: synapse
        property: SYNAPSE_POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-mas-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-mas-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: mas
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: synapse
        property: MAS_POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-linkding-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-linkding-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: linkding
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: linkding
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-miniflux-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: postgres-miniflux-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: miniflux
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: miniflux
        property: POSTGRES_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  enableSuperuserAccess: true
  storage:
    size: 20Gi
    storageClass: local-path
  walStorage:
    size: 10Gi
    storageClass: local-path
  managed:
    roles:
      - name: authentik
        ensure: present
        login: true
        passwordSecret:
          name: postgres-authentik-creds
      - name: forgejo
        ensure: present
        login: true
        passwordSecret:
          name: postgres-forgejo-creds
      - name: synapse
        ensure: present
        login: true
        passwordSecret:
          name: postgres-synapse-creds
      - name: mas
        ensure: present
        login: true
        passwordSecret:
          name: postgres-mas-creds
      - name: nokiy
        ensure: present
        login: true
        passwordSecret:
          name: postgres-nokiy-creds
      - name: linkding
        ensure: present
        login: true
        passwordSecret:
          name: postgres-linkding-creds
      - name: miniflux
        ensure: present
        login: true
        passwordSecret:
          name: postgres-miniflux-creds
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://backup-nokiy-net/mine/postgres/
      endpointURL: https://s3.us-east-005.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: b2-creds
          key: access_key
        secretAccessKey:
          name: b2-creds
          key: secret_key
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: AES256
      data:
        compression: bzip2
        encryption: AES256
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-nokiy
  namespace: postgres
spec:
  name: nokiy
  owner: nokiy
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-authentik
  namespace: postgres
spec:
  name: authentik
  owner: authentik
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-forgejo
  namespace: postgres
spec:
  name: forgejo
  owner: forgejo
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-synapse
  namespace: postgres
spec:
  name: synapse
  owner: synapse
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-mas
  namespace: postgres
spec:
  name: mas
  owner: mas
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-linkding
  namespace: postgres
spec:
  name: linkding
  owner: linkding
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-miniflux
  namespace: postgres
spec:
  name: miniflux
  owner: miniflux
  cluster:
    name: postgres
