apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-creds
  namespace: postgres
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: b2-creds
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
  data:
    - secretKey: access_key
      remoteRef:
        key: b2-backup
        property: ACCESS_KEY
    - secretKey: secret_key
      remoteRef:
        key: b2-backup
        property: SECRET_KEY
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 3
  enableSuperuserAccess: true
  storage:
    size: 20Gi
    storageClass: local-path
  walStorage:
    size: 10Gi
    storageClass: local-path
  managed:
    roles:
    - name: authentik
      ensure: present
      login: true
      passwordSecret:
        name: postgres-authentik
    - name: forgejo
      ensure: present
      login: true
      passwordSecret:
        name: postgres-forgejo
    - name: synapse
      ensure: present
      login: true
      passwordSecret:
        name: postgres-synapse
    - name: mas
      ensure: present
      login: true
      passwordSecret:
        name: postgres-mas
    - name: nokiy
      ensure: present
      login: true
      passwordSecret:
        name: postgres-nokiy
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://backup-nokiy-net/mine/postgres/
      endpointURL: https://s3.us-east-005.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: b2-creds
          key: access_key
        secretAccessKey:
          name: b2-creds
          key: secret_key
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: AES256
      data:
        compression: bzip2
        encryption: AES256
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-rw
  namespace: postgres
spec:
  cluster:
    name: postgres
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "20"
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: postgres
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-nokiy
  namespace: postgres
spec:
  name: nokiy
  owner: nokiy
  cluster:
    name: postgres
