apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        DOMAIN: "https://vault.nokiy.net"
        SSO_ENABLED: "true"
        SSO_ONLY: "true"
        SSO_SIGNUPS_MATCH_EMAIL: "true"
        SSO_AUTHORITY: "https://id.nokiy.net"
        SSO_SCOPE: "openid email profile"
        SSO_PKCE: "true"
        SSO_CLIENT_ID: "{{ .CLIENT_ID }}"
        SSO_CLIENT_SECRET: "{{ .CLIENT_SECRET }}"
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: vaultwarden
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: vaultwarden
        property: CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litestream-secrets
  namespace: vaultwarden
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: litestream-secrets
    template:
      engineVersion: v2
      data:
        litestream.yml: |
          access-key-id: {{ .aws_access_key_id | quote }}
          secret-access-key: {{ .aws_secret_access_key | quote }}

          dbs:
            - path: /data/db.sqlite3
              replicas:
                - type: s3
                  bucket: backup
                  path: vaultwarden-litestream
                  endpoint: https://nokiy.net
                  force-path-style: false
                  age:
                    identities:
                      - {{ .AGE_SECRET_KEY }}
                    recipients:
                      - {{ .AGE_PUBLIC_KEY }}

  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: backup.nokiy.net
        property: ACCESS_KEY
    - secretKey: aws_secret_access_key
      remoteRef:
        key: backup.nokiy.net
        property: SECRET_KEY
    - secretKey: AGE_SECRET_KEY
      remoteRef:
        key: litestream
        property: AGE_SECRET_KEY
    - secretKey: AGE_PUBLIC_KEY
      remoteRef:
        key: litestream
        property: AGE_PUBLIC_KEY
