---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotosocial-secrets
  namespace: gotosocial
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: gotosocial-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: gotosocial
          app.kubernetes.io/part-of: gotosocial
      data:
        GTS_HTTP_PORT: "8080"
        GTS_HOST: "social.nokiy.net"
        GTS_TRUSTED_PROXIES: "10.0.0.0/8,192.168.0.0/16"
        GTS_INSTANCE_LANGUAGE: zh-Hans-CN,en
        GTS_DB_TYPE: sqlite
        GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
        GTS_OIDC_ENABLED: "true"
        GTS_OIDC_ISSUER: "https://auth.nokiy.net/application/o/gotosocial/"
        GTS_OIDC_IDP_NAME: "Nokiy Auth"
        GTS_OIDC_ALLOWED_GROUPS: "gotosocial-admin,gotosocial-user"
        GTS_OIDC_ADMIN_GROUPS: "gotosocial-admin"
        GTS_OIDC_CLIENT_ID: '{{ .GTS_OIDC_CLIENT_ID | toString }}'
        GTS_OIDC_CLIENT_SECRET: '{{ .GTS_OIDC_CLIENT_SECRET | toString }}'
        GTS_STORAGE_BACKEND: s3
        GTS_STORAGE_S3_BUCKET: file
        GTS_STORAGE_S3_ENDPOINT: social.nokiy.net
        GTS_STORAGE_S3_ACCESS_KEY: '{{ .GTS_STORAGE_S3_ACCESS_KEY | toString }}'
        GTS_STORAGE_S3_SECRET_KEY: '{{ .GTS_STORAGE_S3_SECRET_KEY | toString }}'
        GTS_STORAGE_S3_USE_SSL: "true"
        GTS_STORAGE_S3_BUCKET_LOOKUP: "dns"
        GTS_STORAGE_LOCAL_BASE_PATH: /gotosocial/storage
        GTS_WAZERO_COMPILATION_CACHE: /gotosocial/.cache
  data:
    - secretKey: GTS_OIDC_CLIENT_ID
      remoteRef:
        key: gotosocial
        property: CLIENT_ID
    - secretKey: GTS_OIDC_CLIENT_SECRET
      remoteRef:
        key: gotosocial
        property: CLIENT_SECRET
    - secretKey: GTS_STORAGE_S3_ACCESS_KEY
      remoteRef:
        key: gotosocial
        property: ACCESS_KEY
    - secretKey: GTS_STORAGE_S3_SECRET_KEY
      remoteRef:
        key: gotosocial
        property: SECRET_KEY
