---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litestream-secrets
  namespace: gotosocial
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: litestream-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        litestream.yml: |
          access-key-id: {{ .aws_access_key_id | quote }}
          secret-access-key: {{ .aws_secret_access_key | quote }}

          dbs:
            - path: /gotosocial/storage/sqlite.db
              replicas:
                - type: s3
                  bucket: backup
                  path: gotosocial-litestream
                  endpoint: {{ .s3_endpoint | quote }}
                  force-path-style: false
                  age:
                    identities:
                      - {{ .AGE_SECRET_KEY }}
                    recipients:
                      - {{ .AGE_PUBLIC_KEY }}

  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: backup.nokiy.net
        property: ACCESS_KEY
    - secretKey: aws_secret_access_key
      remoteRef:
        key: backup.nokiy.net
        property: SECRET_KEY
    - secretKey: s3_endpoint
      remoteRef:
        key: backup.nokiy.net
        property: ENDPOINT
    - secretKey: AGE_SECRET_KEY
      remoteRef:
        key: litestream
        property: AGE_SECRET_KEY
    - secretKey: AGE_PUBLIC_KEY
      remoteRef:
        key: litestream
        property: AGE_PUBLIC_KEY
