---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litestream-secrets
  namespace: gotosocial
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: litestream-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        litestream.yml: |
          access-key-id: {{ .aws_access_key_id | quote }}
          secret-access-key: {{ .aws_secret_access_key | quote }}

          dbs:
            - path: /gotosocial/storage/sqlite.db
              replicas:
                - type: s3
                  bucket: backup-nokiy-net
                  path: litestream/gotosocial
                  endpoint: s3.us-east-005.backblazeb2.com
                  # force-path-style: false
                  # disabled for https://github.com/benbjohnson/litestream/pull/791
                  # age:
                  #   identities:
                  #     - {{ .AGE_SECRET_KEY }}
                  #   recipients:
                  #     - {{ .AGE_PUBLIC_KEY }}

  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: b2-backup
        property: ACCESS_KEY
    - secretKey: aws_secret_access_key
      remoteRef:
        key: b2-backup
        property: SECRET_KEY
    - secretKey: AGE_SECRET_KEY
      remoteRef:
        key: litestream
        property: AGE_SECRET_KEY
    - secretKey: AGE_PUBLIC_KEY
      remoteRef:
        key: litestream
        property: AGE_PUBLIC_KEY
