apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgres-credentials
  namespace: forgejo
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: forgejo-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: forgejo
        password: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: forgejo
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-env
  namespace: forgejo
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: forgejo-env
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        FORGEJO__server__DOMAIN: '{{ .DOMAIN | toString }}'
        FORGEJO__server__ROOT_URL: 'https://{{ .DOMAIN | toString }}'
        FORGEJO__session__DOMAIN: '{{ .DOMAIN | toString }}'
        FORGEJO__storage__STORAGE_TYPE: minio
        FORGEJO__storage__SERVE_DIRECT: "true"
        FORGEJO__storage__MINIO_BUCKET: '{{ .S3_BUCKET | toString }}'
        FORGEJO__storage__MINIO_ENDPOINT: '{{ .S3_ENDPOINT | toString }}'
        FORGEJO__storage__MINIO_LOCATION: '{{ .S3_LOCATION | toString }}'
        FORGEJO__storage__MINIO_USE_SSL: "true"
        FORGEJO__storage__MINIO_ACCESS_KEY_ID: '{{ .S3_ACCESS_KEY_ID | toString }}'
        FORGEJO__storage__MINIO_SECRET_ACCESS_KEY: '{{ .S3_SECRET_ACCESS_KEY | toString }}'
        FORGEJO__mailer__ENABLED: "true"
        FORGEJO__mailer__SMTP_ADDR: '{{ .SMTP_ADDR | toString }}'
        FORGEJO__mailer__SMTP_PORT: '{{ .SMTP_PORT | toString }}'
        FORGEJO__mailer__PROTOCOL: '{{ .SMTP_PROTOCOL | toString }}'
        FORGEJO__mailer__FROM: '{{ .SMTP_FROM | toString }}'
        FORGEJO__mailer__USER: '{{ .SMTP_USER | toString }}'
        FORGEJO__mailer__PASSWD: '{{ .SMTP_PASSWORD | toString }}'
  data:
    - secretKey: DOMAIN
      remoteRef:
        key: forgejo
        property: DOMAIN
    - secretKey: S3_BUCKET
      remoteRef:
        key: forgejo
        property: S3_BUCKET
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: forgejo
        property: S3_ENDPOINT
    - secretKey: S3_LOCATION
      remoteRef:
        key: forgejo
        property: S3_LOCATION
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: forgejo
        property: S3_ACCESS_KEY_ID
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: forgejo
        property: S3_SECRET_ACCESS_KEY
    - secretKey: SMTP_ADDR
      remoteRef:
        key: forgejo
        property: SMTP_ADDR
    - secretKey: SMTP_PORT
      remoteRef:
        key: forgejo
        property: SMTP_PORT
    - secretKey: SMTP_PROTOCOL
      remoteRef:
        key: forgejo
        property: SMTP_PROTOCOL
    - secretKey: SMTP_FROM
      remoteRef:
        key: forgejo
        property: SMTP_FROM
    - secretKey: SMTP_USER
      remoteRef:
        key: forgejo
        property: SMTP_USER
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: forgejo
        property: SMTP_PASSWORD
