apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "3.5.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
