apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "37.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      replicas: 2
    ports:
      websecure:
        http3:
          enabled: true
    gatewayClass:
      enabled: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
