---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-init
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/forgejo/init
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: k3s
    - name: cnpg
    - name: redis-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/forgejo/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: forgejo-init
    - name: external-secrets-release
    - name: external-secrets-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-release
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/forgejo/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  dependsOn:
    - name: forgejo-secrets
    - name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-config
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/forgejo/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: forgejo-release
    - name: traefik-config
    - name: cert-manager-letsencrypt
