---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/header-echo

patches:
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: echo.yuzu.nokiy.net
      - op: replace
        path: /spec/rules/0/host
        value: echo.yuzu.nokiy.net
    target:
      kind: Ingress
      name: header-echo
