apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- k3s.yaml
- hetzner.yaml
- traefik.yaml
- external-secrets.yaml
- cert-manager.yaml
- tailscale.yaml
- velero.yaml
- cnpg.yaml
- redis-operator.yaml
# - signoz
# - pds
# - gotosocial
- tg-bot
- pocket-id
