apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- external-secrets
- cert-manager
- tailscale
- hetzner
- traefik.yaml
- signoz
- pds
- cnpg.yaml
- redis-operator.yaml
