apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- cilium.yaml
- k3s.yaml
- hetzner.yaml
- traefik.yaml
- external-secrets.yaml
- cert-manager.yaml
- tailscale.yaml
#- velero.yaml
- cnpg.yaml
- redis-operator.yaml
- simple-backup.yaml
- forgejo-runner.yaml
- lgtm.yaml
# - signoz
# - pds
- gotosocial.yaml
# - skypilot.yaml
- header-echo
- nokiy.yaml
- authentik.yaml
- forgejo.yaml
- synapse.yaml
- tg-bot
- pocket-id
- vaultwarden
