apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nokiy
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/nokiy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: cnpg
    - name: redis-operator
    - name: external-secrets-config
    - name: external-dns-release
  patches:
  - patch: |-
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: nokiy-web
        namespace: nokiy
        annotations:
          external-dns.alpha.kubernetes.io/hostname: nokiy.net
          external-dns.alpha.kubernetes.io/ttl: "300"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    target:
      kind: IngressRoute
      name: nokiy-web
      namespace: nokiy
