apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-init
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/traefik/init
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: k3s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-release
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/traefik/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: traefik-init
    - name: cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/traefik/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: traefik-release
    - name: tailscale-release
  patches:
    - target:
        kind: Service
        name: traefik-tailscale
        namespace: traefik
      patch: |-
        - op: add
          path: /metadata/annotations
          value:
            tailscale.com/hostname: yuzu-traefik
