apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-init
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/vector/init
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: k3s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-release
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/vector/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  dependsOn:
    - name: vector-init
    - name: lgtm-release
