apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signoz-tls
  namespace: signoz
spec:
  secretName: signoz-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: signoz.nokiy.net
  dnsNames:
  - signoz.nokiy.net
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-tls
  namespace: signoz
spec:
  secretName: otel-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: otel.nokiy.net
  dnsNames:
  - "otel.nokiy.net"
  - "*.otel.nokiy.net"
