apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: signoz-secrets
  namespace: signoz
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: signoz-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: api_key
      remoteRef:
        key: signoz
        property: API_KEY
