apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: production
spec:
  provider:
    onepassword:
      # cannot use https due to https://github.com/external-secrets/external-secrets/issues/4515
      connectHost: http://onepassword-connect:8080
      # connectHost: https://onepassword-connect:8443
      vaults:
        yuzu.nokiy.net: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: external-secrets
  conditions:
    - namespaceSelector:
        matchLabels:
          nokiy.net/cluster-secret-store: "production"
