apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare
      property: TOKEN
