apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  values:
    logs:
      general:
        level: "DEBUG"
      access:
        enabled: true
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    deployment:
      kind: DaemonSet
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    service:
      enabled: true
      type: ClusterIP
      ipFamilyPolicy: RequireDualStack
      ipFamilies:
        - IPv4
        - IPv6
      # annotations:
      #   io.cilium/lb-ipam-pool: public-pool
      # spec:
      #   externalTrafficPolicy: Cluster
      single: true
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        http3:
          enabled: true
          advertisedPort: 443
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        ingressClass: traefik
      kubernetesIngress:
        allowEmptyServices: true
        ingressClass: traefik
      kubernetesGateway:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
