apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  upgrade:
    force: true
  values:
    logs:
      general:
        level: "DEBUG"
      access:
        enabled: true
    service:
      enabled: true
      type: LoadBalancer
      ipFamilyPolicy: RequireDualStack
      ipFamilies:
        - IPv4
        - IPv6
      annotations:
        kube-vip.io/loadbalancerIPs: "152.53.243.175,2a0a:4cc0:2000:8e66:cafe::1"
      spec:
        externalTrafficPolicy: Local # Preserve client IPs
        healthCheckNodePort: 30932
      single: true
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        http3:
          enabled: true
          advertisedPort: 443
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        ingressClass: traefik
      kubernetesIngress:
        allowEmptyServices: true
        ingressClass: traefik
      kubernetesGateway:
        enabled: true
    hostNetwork: false
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
