---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - init/namespace.yaml
  - release/workload.yaml
  - release/postgres-cluster.yaml
  - secrets/external-secret.yaml
  - config/ingress.yaml
  - config/certificate.yaml

labels:
  - pairs:
      app.kubernetes.io/name: atuin
      app.kubernetes.io/instance: atuin
