apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubeblocks
  namespace: kubeblocks
spec:
  interval: 5m
  chart:
    spec:
      chart: kubeblocks
      version: '1.0.1'
      sourceRef:
        kind: HelmRepository
        name: kubeblocks
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
