apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: simple-backup-operator
  namespace: simple-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: simple-backup-operator
    namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
