apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-secrets
  namespace: miniflux
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: miniflux-secrets
    template:
      engineVersion: v2
      data:
        RUN_MIGRATIONS: "1"
        BASE_URL: "https://rss.nokiy.net"
        DATABASE_URL: "postgres://miniflux:{{ .password }}@pooler-rw.postgres.svc.cluster.local:5432/miniflux"
        FETCH_BILIBILI_WATCH_TIME: "1"
        FETCH_YOUTUBE_WATCH_TIME: "1"
        MEDIA_PROXY_RESOURCE_TYPES: "image,audio,video"
        MEDIA_PROXY_MODE: "all"
        OAUTH2_CLIENT_ID: "{{ .client_id }}"
        OAUTH2_CLIENT_SECRET: "{{ .client_secret }}"
        OAUTH2_OIDC_DISCOVERY_ENDPOINT: "https://id.nokiy.net/.well-known/openid-configuration"
        OAUTH2_OIDC_PROVIDER_NAME: "NOKIY ID"
        OAUTH2_PROVIDER: "oidc"
        OAUTH2_REDIRECT_URL: "https://rss.nokiy.net/oauth2/oidc/callback"
        OAUTH2_USER_CREATION: "1"

  data:
    - secretKey: password
      remoteRef:
        key: miniflux
        property: POSTGRES_PASSWORD
    - secretKey: client_id
      remoteRef:
        key: miniflux
        property: CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: miniflux
        property: CLIENT_SECRET
