apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgres-credentials
  namespace: forgejo
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: forgejo-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: "{{ .POSTGRES_USERNAME }}"
        password: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_USERNAME
      remoteRef:
        key: forgejo
        property: POSTGRES_USERNAME
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: forgejo
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-env
  namespace: forgejo
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: forgejo-env
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        FORGEJO__server__DOMAIN: 'git.nokiy.net'
        FORGEJO__server__ROOT_URL: 'https://git.nokiy.net'
        FORGEJO__session__DOMAIN: 'git.nokiy.net'
        FORGEJO__storage__STORAGE_TYPE: "minio"
        FORGEJO__storage__SERVE_DIRECT: "true"
        FORGEJO__storage__MINIO_BUCKET: "git-nokiy-net"
        FORGEJO__storage__MINIO_ENDPOINT: "t3.storage.dev"
        FORGEJO__storage__MINIO_LOCATION: "auto"
        FORGEJO__storage__MINIO_USE_SSL: "true"
        FORGEJO__storage__MINIO_ACCESS_KEY_ID: '{{ .S3_ACCESS_KEY_ID | toString }}'
        FORGEJO__storage__MINIO_SECRET_ACCESS_KEY: '{{ .S3_SECRET_ACCESS_KEY | toString }}'
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: forgejo
        property: ACCESS_KEY
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: forgejo
        property: SECRET_KEY
