apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: valkey-forgejo
  namespace: forgejo
spec:
  anonymousAuth: true
  nodes: 1
  replicas: 0

  tls: false # Set to true to enable TLS using cert-manager
  certIssuer: ca-cluster-issuer
  certIssuerType: ClusterIssuer

  prometheus: true
  prometheusLabels:
    prometheus: prometheus 

  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
