apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  name: valkey-nokiy
  namespace: nokiy
spec:
  nodes: 1
  replicas: 0

  tls: true
  certIssuer: ca-cluster-issuer
  certIssuerType: ClusterIssuer

  prometheus: true
  prometheusLabels:
    prometheus: prometheus 

  storage:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
