apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: s3
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: backup
    prefix: yuzu
  credential:
    name: velero-s3-credentials
    key: config.toml
  config:
    s3Url: nokiy.net
    region: auto
    profile: "default"
