apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tsync
  namespace: tsync
  labels:
    app.kubernetes.io/name: tsync
    app.kubernetes.io/instance: tsync
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: tsync
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: tsync
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: TAILSCALE_TAILNET
      remoteRef:
        key: tsync
        property: TAILSCALE_TAILNET
    - secretKey: TAILSCALE_API_KEY
      remoteRef:
        key: tsync
        property: TAILSCALE_API_KEY
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: tsync
        property: CLOUDFLARE_API_TOKEN
    - secretKey: CLOUDFLARE_ZONE_ID
      remoteRef:
        key: tsync
        property: CLOUDFLARE_ZONE_ID
    - secretKey: CLOUDFLARE_DOMAIN
      remoteRef:
        key: tsync
        property: CLOUDFLARE_DOMAIN
    - secretKey: CLOUDFLARE_BASE_DOMAIN
      remoteRef:
        key: tsync
        property: CLOUDFLARE_BASE_DOMAIN
