apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-secrets
  namespace: linkding
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: linkding-secrets
    template:
      engineVersion: v2
      data:
        LD_ENABLE_OIDC: "True"
        OIDC_OP_AUTHORIZATION_ENDPOINT: "https://id.nokiy.net/authorize"
        OIDC_OP_TOKEN_ENDPOINT: "https://id.nokiy.net/api/oidc/token"
        OIDC_OP_USER_ENDPOINT: "https://id.nokiy.net/api/oidc/userinfo"
        OIDC_OP_JWKS_ENDPOINT: "https://id.nokiy.net/.well-known/jwks.json"
        OIDC_RP_CLIENT_ID: "{{ .client_id }}"
        OIDC_RP_CLIENT_SECRET: "{{ .client_secret }}"
        OIDC_RP_SIGN_ALGO: RS256
        OIDC_USE_PKCE: "True"
        OIDC_VERIFY_SSL: "True"
        OIDC_RP_SCOPES: "openid email profile"
        OIDC_USERNAME_CLAIM: "preferred_username"
        LD_LOG_X_FORWARDED_FOR: "true"
        LD_DB_ENGINE: postgres
        LD_DB_DATABASE: linkding
        LD_DB_USER: linkding
        LD_DB_PASSWORD: "{{ .password }}"
        LD_DB_HOST: pooler-rw.postgres.svc.cluster.local
        LD_DB_PORT: "5432"

  data:
    - secretKey: password
      remoteRef:
        key: linkding
        property: POSTGRES_PASSWORD
    - secretKey: client_id
      remoteRef:
        key: linkding
        property: CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: linkding
        property: CLIENT_SECRET
