apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotosocial
commonLabels:
  app.kubernetes.io/name: gotosocial
  app.kubernetes.io/part-of: gotosocial
resources:
  - namespace.yaml
  - externalsecret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
