apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial-data
  namespace: gotosocial
  labels:
    app.kubernetes.io/name: gotosocial
    app.kubernetes.io/part-of: gotosocial
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
