apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: public-only
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 0.0.0.0/0
    ipStrategy:
      excludedIPs:
        - 100.64.0.0/10
