apiVersion: v1
kind: Service
metadata:
  name: traefik-tailscale
  namespace: traefik
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik
  ports:
    - name: websecureinternal
      port: 443
      targetPort: 9443
      protocol: TCP
    - name: webinternal
      port: 80
      targetPort: 9080
      protocol: TCP
