apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-tailscale
  namespace: traefik
  annotations:
    tailscale.com/funnel: "false"
    tailscale.com/tailnet-fqdn: yuzu-traefik.rya-pleco.ts.net
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: traefik
      port:
        number: 443
  tls:
    - hosts:
        - yuzu-traefik
