apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials
  namespace: smb-csi
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: smb-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: "{{ .SMB_USERNAME }}"
        password: "{{ .SMB_PASSWORD }}"
        domain: "{{ .SMB_DOMAIN }}"
  data:
  - secretKey: SMB_USERNAME
    remoteRef:
      key: smb-csi
      property: USERNAME
  - secretKey: SMB_PASSWORD
    remoteRef:
      key: smb-csi
      property: PASSWORD
  - secretKey: SMB_DOMAIN
    remoteRef:
      key: smb-csi
      property: DOMAIN
