---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials-data
  namespace: smb-csi
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: smb-credentials-data
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: "{{ .SMB_USERNAME }}"
        password: "{{ .SMB_PASSWORD }}"
        domain: "{{ .SMB_DOMAIN }}"
        source: "{{ .SMB_SOURCE }}"
  data:
  - secretKey: SMB_USERNAME
    remoteRef:
      key: smb-csi-data
      property: USERNAME
  - secretKey: SMB_PASSWORD
    remoteRef:
      key: smb-csi-data
      property: PASSWORD
  - secretKey: SMB_DOMAIN
    remoteRef:
      key: smb-csi-data
      property: DOMAIN
  - secretKey: SMB_SOURCE
    remoteRef:
      key: smb-csi-data
      property: SOURCE
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-credentials-backup
  namespace: smb-csi
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: smb-credentials-backup
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: "{{ .SMB_USERNAME }}"
        password: "{{ .SMB_PASSWORD }}"
        domain: "{{ .SMB_DOMAIN }}"
        source: "{{ .SMB_SOURCE }}"
  data:
  - secretKey: SMB_USERNAME
    remoteRef:
      key: smb-csi-backup
      property: USERNAME
  - secretKey: SMB_PASSWORD
    remoteRef:
      key: smb-csi-backup
      property: PASSWORD
  - secretKey: SMB_DOMAIN
    remoteRef:
      key: smb-csi-backup
      property: DOMAIN
  - secretKey: SMB_SOURCE
    remoteRef:
      key: smb-csi-backup
      property: SOURCE
