---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arpk-secrets
  namespace: arpk
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: arpk-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      data:
        ARPK_PORT: "1188"
        ARPK_LLM_BASE_URL: "{{ .llm_base_url | toString }}"
        ARPK_LLM_MODEL: "{{ .llm_model | toString }}"
        ARPK_LLM_API_KEY: "{{ .llm_api_key | toString }}"
  data:
    - secretKey: llm_base_url
      remoteRef:
        key: arpk
        property: BASE_URL
    - secretKey: llm_model
      remoteRef:
        key: arpk
        property: MODEL
    - secretKey: llm_api_key
      remoteRef:
        key: arpk
        property: API_KEY
