---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: arpk
      app.kubernetes.io/instance: arpk
