apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
  namespace: flux-system
spec:
  interval: 1m
  path: ./common/forgejo-runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  wait: true
  dependsOn:
    - name: k3s
    - name: external-secrets-config
  patches:
    - target:
        kind: HelmRelease
        name: forgejo-runner
        namespace: forgejo-runner
      patch: |-
        - op: replace
          path: /spec/values/runner/config/name
          value: unit-runner
        - op: add
          path: /spec/values/runner/config/file/runner/labels/-
          value: "amd64:docker://git.nokiy.net/actions/runner:latest"
        - op: add
          path: /spec/values/resources
          value:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
        - op: add
          path: /spec/values/dind
          value:
            resources:
              limits:
                cpu: "3500m"
                memory: 6Gi
              requests:
                cpu: 250m
                memory: 512Mi
