apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- cilium.yaml
- k3s.yaml
- traefik.yaml
- external-secrets.yaml
- cert-manager.yaml
- tailscale.yaml
- simple-backup.yaml
- cnpg.yaml
- redis-operator.yaml
- forgejo-runner.yaml
