apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: greptimedb-standalone
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: greptimedb-standalone
      version: "0.2.12"
      sourceRef:
        kind: HelmRepository
        name: greptime
        namespace: flux-system
  values:
    persistence:
      size: 5Gi
      storageClass: sata
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "9.4.5"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    imageRenderer:
      image:
        repository: greptime/grafana-greptimedb
        tag: 11.2.5-greptime-v2.0.7
