apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: greptime
  namespace: flux-system
spec:
  interval: 5m
  url: https://greptimeteam.github.io/helm-charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vector
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.vector.dev
