apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: greptimedb-standalone
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: greptimedb-standalone
      version: "0.2.12"
      sourceRef:
        kind: HelmRepository
        name: greptime
        namespace: flux-system
  values:
    annotations:
      operator.1password.io/item-path: "vaults/cake.nokiy.net/items/greptimedb"
      operator.1password.io/item-name: "greptimedb"
      operator.1password.io/auto-restart: "true"
    objectStorage:
      s3:
        root: greptimedb/cake.nokiy.net
        bucket: telemetry-storage
        region: auto
        endpoint: nokiy.net
    persistence:
      size: 5Gi
      storageClass: sata
  valueFrom:
    - kind: Secret
      name: greptimedb
      valuesKey: ACCESS_KEY
      targetPath: objectStorage.credentials.accessKeyId
    - kind: Secret
      name: greptimedb
      valuesKey: SECRET_KEY
      targetPath: objectStorage.credentials.secretAccessKey
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "9.4.5"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    annotations:
      operator.1password.io/item-path: "vaults/cake.nokiy.net/items/grafana"
      operator.1password.io/item-name: "grafana"
      operator.1password.io/auto-restart: "true"
    admin:
      existingSecret: grafana
      userKey: username
      passwordKey: password
    plugins:
      - https://github.com/GreptimeTeam/greptimedb-grafana-datasource/releases/download/v2.0.7/info8fcc-greptimedb-datasource.zip;greptimedb-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: GreptimeDB
            isDefault: true
            url: http://greptimedb-standalone:9000
            type: greptimedb-datasource
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: vector
      version: "0.46.0"
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
  values:
    customConfig:
      sources:
        internal_logs:
          type: internal_logs
        internal_metrics:
          type: internal_metrics
        vector_in:
          type: vector
          address: "0.0.0.0:9000"
      sinks:
        greptimedb_metrics:
          type: greptimedb_metrics
          inputs:
            - *_metrics
          endpoint: "greptimedb-standalone:4001"
          dbname: "metrics"
          new_naming: true
        greptimedb_logs:
          type: greptimedb_logs
          inputs:
            - *_logs
          endpoint: "http://greptimedb-standalone:4000"
          dbname: "logs"
          table: "logs"
          compression: "none"
