apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    nokiy.net/cluster-secret-store: "production"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale-traefik
  namespace: flux-system
spec:
  interval: 12h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-traefik
  namespace: tailscale
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "39.0.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale-traefik
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      loadBalancerClass: tailscale
      annotations:
        tailscale.com/hostname: ${CLUSTER}-traefik
      externalTrafficPolicy: Local
      single: true
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: tailscale-traefik
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true
        ingressClass: tailscale-traefik
      kubernetesIngress:
        allowEmptyServices: true
        ingressClass: tailscale-traefik
      kubernetesGateway:
        enabled: true
    ports:
      web:
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 100.64.0.0/10
            - 172.16.0.0/12
            - 192.168.0.0/16
      websecure:
        http3:
          enabled: true
          advertisedPort: 443
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 100.64.0.0/10
            - 172.16.0.0/12
            - 192.168.0.0/16
    gatewayClass:
      enabled: true
      name: tailscale-traefik
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
