---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/beszel

patches:
  - patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: monitor.nokiy.net
      - op: replace
        path: /spec/tls/0/secretName
        value: monitor-tls
      - op: replace
        path: /spec/rules/0/host
        value: monitor.nokiy.net
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: monitor.nokiy.net
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1ttl
        value: "300"
    target:
      kind: Ingress
      name: beszel
