apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: skypilot-secrets
  namespace: skypilot
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: skypilot-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      data:
        client-id: "{{ .CLIENT_ID }}"
        client-secret: "{{ .CLIENT_SECRET }}"
  data:
    - secretKey: CLIENT_ID
      remoteRef:
        key: skypilot
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: skypilot
        property: CLIENT_SECRET
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: skypilot
  namespace: skypilot
spec:
  interval: 1h
  chart:
    spec:
      chart: skypilot-nightly
      version: "1.0.0-dev.20260125"
      sourceRef:
        kind: HelmRepository
        name: skypilot
        namespace: flux-system
  values:
    rbac:
      manageSystemComponents: false
    apiService:
      skipResourceCheck: true
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
    auth:
      oauth:
        enabled: true
        oidc-issuer-url: https://id.nokiy.net
        client-details-from-secret: "skypilot-secrets"
        session-store-type: redis
        redis-url: redis://valkey-skypilot:6379
    storage:
      enabled: false
    ingress:
      enabled: true
      host: sky.nokiy.net
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: sky.nokiy.net
    ingress-nginx:
      enabled: false
