apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: '0.26.0'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    crds:
      enabled: true
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
