apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- cert-manager
- common
- tailscale
- cnpg
# - kubeblocks
- traefik
- forgejo-runner
- sing-box
- greptime
- self-nokiy-net
# - coder
