apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  refreshInterval: "1h"
  refreshPolicy: Periodic
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    name: forgejo-runner
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: TOKEN
      remoteRef:
        key: forgejo-runner
        property: TOKEN
