apiVersion: apps/v1
kind: Deployment
metadata:
  name: huggingface-daily-papers
  namespace: tg-bot
  labels:
    app.kubernetes.io/name: huggingface-daily-papers
    app.kubernetes.io/instance: huggingface-daily-papers
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: huggingface-daily-papers
      app.kubernetes.io/instance: huggingface-daily-papers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: huggingface-daily-papers
        app.kubernetes.io/instance: huggingface-daily-papers
    spec:
      containers:
        - name: huggingface-daily-papers
          image: ghcr.io/reonokiy/telegram-huggingface-daily-papers-bot:latest@sha256:67d925f1e706e9d09c2213c468f0dc318eed61b05056f28b472352f9dd64a7ed
          envFrom:
            - secretRef:
                name: huggingface-daily-papers-secrets
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: huggingface-daily-papers-data
