apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phoenix-chart
  namespace: flux-system
spec:
  interval: 12h
  url: oci://registry-1.docker.io/arizephoenix/phoenix-helm
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "7.0.9"
