apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phoenix-secrets
  namespace: phoenix
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: phoenix-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: phoenix
        property: POSTGRES_PASSWORD
    - secretKey: PHOENIX_SECRET
      remoteRef:
        key: phoenix
        property: PHOENIX_SECRET
    - secretKey: PHOENIX_ADMIN_SECRET
      remoteRef:
        key: phoenix
        property: PHOENIX_ADMIN_SECRET
    - secretKey: POCKET_ID_CLIENT_ID
      remoteRef:
        key: phoenix
        property: POCKET_ID_CLIENT_ID
    - secretKey: POCKET_ID_CLIENT_SECRET
      remoteRef:
        key: phoenix
        property: POCKET_ID_CLIENT_SECRET
