---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ferretdb-nokiy
  namespace: self-nokiy-net
spec:
  instances: 1
  imageName: 'ghcr.io/ferretdb/postgres-documentdb:17-0.106.0-ferretdb-2.5.0'
  postgresUID: 999
  postgresGID: 999
  enableSuperuserAccess: true

  storage:
    size: 5Gi

  postgresql:
    shared_preload_libraries:
      - pg_cron
      - pg_documentdb_core
      - pg_documentdb
    parameters:
      cron.database_name: 'postgres'
    pg_hba:
      - host all all 127.0.0.1/32 scram-sha-256
      - host all all ::1/128 scram-sha-256
      - host all all all scram-sha-256

  bootstrap:
    initdb:
      postInitSQL:
        - 'CREATE EXTENSION IF NOT EXISTS documentdb CASCADE;'
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-postgres-ferretdb-nokiy-rw
  namespace: self-nokiy-net
spec:
  cluster:
    name: postgres-ferretdb-nokiy
  instances: 1
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
  namespace: self-nokiy-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:2.5.0
          ports:
            - containerPort: 27017
          env:
            - name: FERRETDB_POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-ferretdb-nokiy-superuser 
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: ferretdb-nokiy-service
  namespace: self-nokiy-net
spec:
  selector:
    app: ferretdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort
