apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: greptimedb-standalone
  namespace: self-nokiy-net
spec:
  interval: 5m
  chart:
    spec:
      chart: greptimedb-standalone
      version: "0.2.12"
      sourceRef:
        kind: HelmRepository
        name: greptime
        namespace: flux-system
  values:
    persistence:
      size: 10Gi
      storageClass: sata
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
