---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-nokiy
  namespace: self-nokiy-net
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/cake.nokiy.net/items/postgres-nokiy"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-nokiy
  namespace: self-nokiy-net
spec:
  instances: 3
  storage:
    size: 5Gi
  managed:
    roles:
    - name: nokiy
      ensure: present
      login: true
      superuser: false
      passwordSecret:
        name: postgres-nokiy
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler-postgres-nokiy-rw
  namespace: self-nokiy-net
spec:
  cluster:
    name: postgres-nokiy
  instances: 3
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
  serviceTemplate:
    metadata:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: postgres-nokiy-pooler-rw
    spec:
      type: LoadBalancer
      loadBalancerClass: tailscale
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres
  namespace: self-nokiy-net
spec:
  name: nokiy
  owner: nokiy
  cluster:
    name: postgres-nokiy
