apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nokiy-cms-secrets
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: nokiy-cms-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      config.toml: |
        DB_HOST: "pooler-postgres-rw"
        DB_PORT: "5432"
        DB_NAME: "documents"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: nokiy-cms
        property: DB_USERNAME
    - secretKey: password
      remoteRef:
        key: nokiy-cms
        property: DB_PASSWORD
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nokiy-cms
  labels:
    app: nokiy-cms
spec:
  serviceName: nokiy-cms
  replicas: 2
  selector:
    matchLabels:
      app: nokiy-cms
  template:
    metadata:
      labels:
        app: nokiy-cms
    spec:
      initContainers:
      - name: init-config
        image: busybox:1.36
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
          - |
            cat <<EOF > /config/nokiy.config.yaml
            log_level: info
            db:
              uri: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
            EOF
            echo "Configuration file created successfully"
            cat /config/nokiy.config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /config
        envFrom:
        - secretRef:
            name: nokiy-cms-secrets
      containers:
      - name: nokiy-cms
        image: git.nokiy.net/reonokiy/nokiy:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        args: ["server", "start"]
        volumeMounts:
        - name: config-volume
          mountPath: /app
        - name: data
          mountPath: /data
      volumes:
      - name: config-volume
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
