---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-repository.yaml
- vm-operator.yaml
- vm-cluster.yaml
- vl-cluster.yaml
- vm-auth.yaml
- vm-users.yaml
- grafana.yaml
labels:
- pairs:
    app.kubernetes.io/name: vm
    app.kubernetes.io/instance: vm
