---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Disabled resources (not included):
# - configmap.yaml
# - wellknown-deployment.yaml
# - wellknown-service.yaml
# - wellknown-ingress.yaml
- pvc.yaml
- secrets.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
