apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-postgres-credentials
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: synapse-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: "synapse"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: synapse
        property: SYNAPSE_POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mas-postgres-credentials
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: mas-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: "mas"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: synapse
        property: MAS_POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-config
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: synapse-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        homeserver.yaml: |
          ## Server Part
          server_name: nokiy.net
          web_client_location: https://element.nokiy.net
          public_baseurl: https://synapse.nokiy.net/
          serve_server_wellknown: true
          ip_range_blacklist:
            - '127.0.0.0/8'
            - '10.0.0.0/8'
            - '172.16.0.0/12'
            - '192.168.0.0/16'
            - '100.64.0.0/10'
            - '192.0.0.0/24'
            - '169.254.0.0/16'
            - '192.88.99.0/24'
            - '198.18.0.0/15'
            - '192.0.2.0/24'
            - '198.51.100.0/24'
            - '203.0.113.0/24'
            - '224.0.0.0/4'
            - '::1/128'
            - 'fe80::/10'
            - 'fc00::/7'
            - '2001:db8::/32'
            - 'ff00::/8'
            - 'fec0::/10'
          listeners:
            - port: 8008
              bind_addresses:
                - 0.0.0.0
              type: http
              tls: false
              x_forwarded: true
              resources:
                - names: [client, federation]
                  compress: false

          ## Database Part
          database:
            name: psycopg2
            txn_limit: 10000
            args:
              user: synapse
              password: "{{ .postgres_password }}"
              dbname: synapse
              host: postgres-rw.postgres.svc.cluster.local
              port: 5432
              cp_min: 5
              cp_max: 10

          media_store_path: /data/media_store
          signing_key_path: "/data/key/homeserver.signing.key"
          trusted_key_servers:
            - server_name: "matrix.org"

          ## Homeserver Blocking
          admin_contact: 'mailto:contact+synapse@nokiy.net'

          ## TLS
          federation_verify_certificates: true
          federation_client_minimum_tls_version: "1.2"

          ## Storage Backend
          dynamic_thumbnails: true
          thumbnail_sizes:
            - width: 32
              height: 32
              method: crop
            - width: 96
              height: 96
              method: crop
            - width: 320
              height: 240
              method: scale
            - width: 640
              height: 480
              method: scale
            - width: 800
              height: 600
              method: scale
          media_retention:
            local_media_lifetime: 1y
            remote_media_lifetime: 14d
          url_preview_enabled: true
          url_preview_ip_range_blacklist:
            - '127.0.0.0/8'
            - '10.0.0.0/8'
            - '172.16.0.0/12'
            - '192.168.0.0/16'
            - '100.64.0.0/10'
            - '192.0.0.0/24'
            - '169.254.0.0/16'
            - '192.88.99.0/24'
            - '198.18.0.0/15'
            - '192.0.2.0/24'
            - '198.51.100.0/24'
            - '203.0.113.0/24'
            - '224.0.0.0/4'
            - '::1/128'
            - 'fe80::/10'
            - 'fc00::/7'
            - '2001:db8::/32'
            - 'ff00::/8'
            - 'fec0::/10'
          url_preview_accept_language:
            - 'zh-CN'
            - 'en-US;q=0.9'
            - 'en-UK;q=0.8'
            - "*;q=0.7"
          oembed:
            disable_default_providers: false
            additional_providers: []

          ## TURN
          turn_uris:
            - turn:turn.nokiy.net:3478?transport=udp
            - turn:turn.nokiy.net:3478?transport=tcp
          turn_shared_secret: "{{ .turn_shared_secret }}"
          turn_user_lifetime: 1h

          ## Registration
          enable_registration: false
          enable_set_displayname: true

          ## Rooms
          encryption_enabled_by_default_for_room_type: "invite"
          user_directory:
            enabled: true
            search_all_users: true
            prefer_local_users: true
            show_locked_users: true
          server_notices:
            system_mxid_localpart: server
            system_mxid_display_name: "Server Notices"
            system_mxid_avatar_url: "mxc://example.com/oumMVlgDnLYFaPVkExemNVVZ"
            room_name: "Server Notices"
            room_avatar_url: "mxc://example.com/oumMVlgDnLYFaPVkExemNVVZ"
            room_topic: "Room used by your server admin to notice you of important information"
            auto_join: true

          redis:
            enabled: true
            host: valkey-synapse.synapse.svc.cluster.local
            port: 6379
          pid_file: "/data/homeserver.pid"
          media_store_path: "/data/media_store"
          max_upload_size: 200M

          push:
            enabled: true
            include_content: false
            group_unread_count_by_room: true
            jitter_delay: "3s"

          report_stats: false

          experimental_features:
            # MAS Auth
            msc3861:
              enabled: true
              # Synapse will call `{issuer}/.well-known/openid-configuration` to get the OIDC configuration
              issuer: http://mas:8080/
              # Matches the `client_id` in the auth service config
              client_id: "{{ .mas_client_id }}"
              # Matches the `client_auth_method` in the auth service config
              client_auth_method: client_secret_basic
              # Matches the `client_secret` in the auth service config
              client_secret: "{{ .mas_client_secret }}"
              # Matches the `matrix.secret` in the auth service config
              admin_token: "{{ .mas_admin_token }}"
              # URL to advertise to clients where users can self-manage their account
              # Defaults to the URL advertised by MAS, e.g. `https://{public_mas_domain}/account/`
              account_management_url: "https://auth.synapse.nokiy.net/account/"
              # URL which Synapse will use to introspect access tokens
              # Defaults to the URL advertised by MAS, e.g. `https://{public_mas_domain}/oauth2/introspect`
              # This is useful to override if Synapse has a way to call the auth service's
              # introspection endpoint directly, skipping intermediate reverse proxies
              introspection_endpoint: "https://auth.synapse.nokiy.net/oauth2/introspect"
        homeserver.signing.key: |
          {{ .homeserver_signing_key }}
        homeserver.signing.key.2: |
          {{ .homeserver_signing_key_2 }}
        mas.yaml: |
          http:
            listeners:
            - name: web
              resources:
              - name: discovery
              - name: human
              - name: oauth
              - name: compat
              - name: graphql
              - name: assets
              binds:
              - address: '[::]:8080'
              proxy_protocol: false
            - name: internal
              resources:
              - name: health
              binds:
              - host: localhost
                port: 8081
              proxy_protocol: false
            trusted_proxies:
            - 192.168.0.0/16
            - 172.16.0.0/12
            - 10.0.0.0/10
            - 127.0.0.1/8
            - fd00::/8
            - ::1/128
            public_base: https://auth.synapse.nokiy.net/
            issuer: https://auth.synapse.nokiy.net/
          database:
            uri: "postgresql://mas:{{ .mas_password }}@postgres-rw.postgres.svc.cluster.local/mas"
            max_connections: 10
            min_connections: 0
            connect_timeout: 30
            idle_timeout: 600
            max_lifetime: 1800
          email:
            from: '"Authentication Service" <root@localhost>'
            reply_to: '"Authentication Service" <root@localhost>'
            transport: blackhole
          secrets:
            encryption: "{{ .mas_encryption_secret }}"
            keys:
            - kid: UsiGpeGObM
              key: |-
                {{- .mas_UsiGpeGObM_private_key | nindent 6 }}
            - kid: l0yoBLacCz
              key: |-
                {{- .mas_l0yoBLacCz_private_key | nindent 6 }}
            - kid: ymYrNtji6e
              key: |-
                {{- .mas_ymYrNtji6e_private_key | nindent 6 }}
            - kid: 0452osHf6H
              key: |-
                {{- .mas_0452osHf6H_private_key | nindent 6 }}
          passwords:
            enabled: true
            schemes:
            - version: 1
              algorithm: bcrypt
            - version: 2
              algorithm: argon2id
            minimum_complexity: 3
          upstream_oauth2:
            providers:
              - id: 01HFRQFT5QFMJFGF01P7JAV2ME
                human_name: Nokiy Auth
                synapse_idp_id: oidc-nokiy_auth
                issuer: "https://auth.nokiy.net/application/o/synapse/"
                client_id: "{{ .mas_upstream_client_id }}"
                client_secret: "{{ .mas_upstream_client_secret }}"
                token_endpoint_auth_method: client_secret_basic
                scope: "openid profile email"
                claims_imports:
                  localpart:
                    action: require
                    template: "{{`{{ user.preferred_username }}`}}"
                  displayname:
                    action: suggest
                    template: "{{`{{ user.name }}`}}"
                  email:
                    action: suggest
                    template: "{{`{{ user.email }}`}}"
                    set_email_verification: always
          clients:
            - client_id: "{{ .mas_client_id }}"
              client_auth_method: client_secret_basic
              client_secret: "{{ .mas_client_secret }}"
          matrix:
            kind: synapse
            homeserver: nokiy.net
            secret: "{{ .mas_admin_token }}"
            endpoint: http://synapse:8008/
          policy:
            data:
              client_registration:
                allow_host_mismatch: true
  data:
    - secretKey: postgres_password
      remoteRef:
        key: synapse
        property: SYNAPSE_POSTGRES_PASSWORD
    - secretKey: turn_shared_secret
      remoteRef:
        key: synapse
        property: TURN_SHARED_SECRET
    - secretKey: mas_client_id
      remoteRef:
        key: synapse
        property: MAS_CLIENT_ID
    - secretKey: mas_client_secret
      remoteRef:
        key: synapse
        property: MAS_CLIENT_SECRET
    - secretKey: mas_admin_token
      remoteRef:
        key: synapse
        property: MAS_ADMIN_TOKEN
    - secretKey: mas_password
      remoteRef:
        key: synapse
        property: MAS_POSTGRES_PASSWORD
    - secretKey: homeserver_signing_key
      remoteRef:
        key: synapse
        property: SIGNING_KEY
    - secretKey: homeserver_signing_key_2
      remoteRef:
        key: synapse
        property: SIGNING_KEY2
    - secretKey: mas_UsiGpeGObM_private_key
      remoteRef:
        key: synapse
        property: MAS_UsiGpeGObM_PRIVATE_KEY
    - secretKey: mas_l0yoBLacCz_private_key
      remoteRef:
        key: synapse
        property: MAS_l0yoBLacCz_PRIVATE_KEY
    - secretKey: mas_ymYrNtji6e_private_key
      remoteRef:
        key: synapse
        property: MAS_ymYrNtji6e_PRIVATE_KEY
    - secretKey: mas_0452osHf6H_private_key
      remoteRef:
        key: synapse
        property: MAS_0452osHf6H_PRIVATE_KEY
    - secretKey: mas_encryption_secret
      remoteRef:
        key: synapse
        property: MAS_ENCRYPTION_SECRET
    - secretKey: mas_upstream_client_id
      remoteRef:
        key: synapse
        property: MAS_UPSTREAM_CLIENT_ID
    - secretKey: mas_upstream_client_secret
      remoteRef:
        key: synapse
        property: MAS_UPSTREAM_CLIENT_SECRET
