---
# Nginx deployment to serve well-known files
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-wellknown
  namespace: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-wellknown
  template:
    metadata:
      labels:
        app: matrix-wellknown
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wellknown
              mountPath: /usr/share/nginx/html/.well-known/matrix
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
      volumes:
        - name: wellknown
          configMap:
            name: matrix-wellknown
        - name: nginx-config
          configMap:
            name: matrix-wellknown-nginx
