apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h
  url: oci://dp.apps.rancher.io/charts/local-path-provisioner
  ref:
    tag: "0.0.32"
