---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - init
  - secrets
  - release
  - config
labels:
  - pairs:
      app.kubernetes.io/name: nofx
      app.kubernetes.io/instance: nofx
      app.kubernetes.io/part-of: nofx
