apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- init
- secrets
- database
- redis
- app
- config

labels:
- pairs:
    app.kubernetes.io/name: usesend
    app.kubernetes.io/instance: usesend
