apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  secretStoreRef:
    name: production
    kind: SecretStore
  target:
    name: velero-s3-credentials
    template:
      engine: gotpl
      data:
        config.toml: |
          [default]
          aws_access_key_id = {{ .aws_access_key_id | quote }}
          aws_secret_access_key = {{ .aws_secret_access_key | quote }}
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: velero
        property: ACCESS_KEY
    - secretKey: aws_secret_access_key
      remoteRef:
        key: velero
        property: SECRET_KEY
