apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
    namespace: flux-system
  values:
    runner:
      config:
        name: "cake-nokiy-net"
        instance: https://git.nokiy.net
        create: true
        existingSecret: ""
        file:
          log:
            level: "info"
          runner:
            file: ".runner"
            capacity: 1
            envs:
              A_TEST_ENV_NAME_1: null
              A_TEST_ENV_NAME_2: null
              DOCKER_HOST: tcp://127.0.0.1:2376
              DOCKER_TLS_VERIFY: 1
              DOCKER_CERT_PATH: /certs/client
            labels:
              - "ubuntu-latest:docker://node:22-trixie"
          container:
            network: "host"
            enable_ipv6: false
            privileged: false
            options: -v /certs/client:/certs/client
            valid_volumes:
              - /certs/client
  valuesFrom:
    - kind: Secret
      name: forgejo-runner
      valuesKey: TOKEN
      targetPath: runner.config.token
