apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
    namespace: flux-system
  values:
    runner:
      config:
        name: "cake-nokiy-net"
        instance: https://git.nokiy.net
        create: true
        file:
          log:
            level: "info"
          runner:
            file: ".runner"
            capacity: 3
            envs:
              DOCKER_HOST: tcp://127.0.0.1:2376
            labels:
              - "ubuntu-latest:docker://mirror.gcr.io/library/node:22-trixie-slim"
          container:
            network: "host"
            enable_ipv6: false
            privileged: false
  valuesFrom:
    - kind: Secret
      name: forgejo-runner
      valuesKey: TOKEN
      targetPath: runner.config.token
