apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
spec:
  interval: 5m
  chart:
    spec:
      chart: forgejo-runner
      version: "0.6.6"
      sourceRef:
        kind: HelmRepository
        name: forgejo-runner
        namespace: flux-system
  values:
    runner:
      config:
        create: true
        existingSecret: ""
        file:
          log:
            level: "info"
          runner:
            file: ".runner"
            capacity: 1
            envs:
              A_TEST_ENV_NAME_1: null
              A_TEST_ENV_NAME_2: null
              DOCKER_HOST: tcp://127.0.0.1:2376
              DOCKER_TLS_VERIFY: 1
              DOCKER_CERT_PATH: /certs/client
            labels:
              - "ubuntu-latest:docker://node:22-trixie"
          container:
            network: "host"
            enable_ipv6: false
            privileged: false
            options: -v /certs/client:/certs/client
            valid_volumes:
              - /certs/client
