apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notion-sync-secrets
  namespace: nokiy
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: notion-sync-secrets
    template:
      engineVersion: v2
      data:
        config.toml: |
          [notion]
          api_key = "{{ .NOTION_TOKEN }}"

          [queue]
          redis_url = "redis://valkey-nokiy.nokiy.svc.cluster.local:6379"
          name = "notion-sync"

          [webhook]
          host = "0.0.0.0"
          port = 3000
          secret = ""
          max_age_seconds = 300

          [[database]]
          id = "2b7934bb5e6280a08cabf4777ef8c06e"
          [[database.storage]]
          type = "b2"
          root = "/notion/reonokiy/research"
          application_key_id = "{{ .B2_APPLICATION_KEY_ID }}"
          application_key = "{{ .B2_APPLICATION_KEY }}"
          bucket = "{{ .B2_BUCKET }}"
          bucket_id = "{{ .B2_BUCKET_ID }}"
          [database.properties.map]
          "名称" = "title"
          "创建时间" = "created_at"
          "发布时间" = "published_at"
          "研究领域" = "tags"
          [database.properties.filter]
          includes = ["名称", "创建时间", "发布时间", "研究领域"]

          [[database]]
          id = "6b06900e81d64dc2a97280953ea1cc00"
          [[database.storage]]
          type = "b2"
          root = "/notion/reonokiy/notes"
          application_key_id = "{{ .B2_APPLICATION_KEY_ID }}"
          application_key = "{{ .B2_APPLICATION_KEY }}"
          bucket = "{{ .B2_BUCKET }}"
          bucket_id = "{{ .B2_BUCKET_ID }}"
          [database.properties.map]
          "笔记" = "title"
          "描述" = "description"
          "时间" = "created_at"
          "标签" = "tags"
          [database.properties.filter]
          includes = ["笔记", "描述", "时间", "标签"]

  data:
    - secretKey: B2_APPLICATION_KEY_ID
      remoteRef:
        key: b2-data
        property: APPLICATION_KEY_ID
    - secretKey: B2_APPLICATION_KEY
      remoteRef:
        key: b2-data
        property: APPLICATION_KEY
    - secretKey: B2_BUCKET
      remoteRef:
        key: b2-data
        property: BUCKET
    - secretKey: B2_BUCKET_ID
      remoteRef:
        key: b2-data
        property: BUCKET_ID
    - secretKey: NOTION_TOKEN
      remoteRef:
        key: notion
        property: TOKEN
