apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: cert-manager
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: cloudflare-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare
        property: TOKEN
