apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgres-credentials
  namespace: forgejo
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: forgejo-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: forgejo
        password: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: forgejo
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-env
  namespace: forgejo
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: forgejo-env
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: forgejo
