apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-secrets
  namespace: atuin
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: atuin-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: ATUIN_DB_PASSWORD
    remoteRef:
      key: atuin-db-password
      property: POSTGRES_PASSWORD
