apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: usesend-app-secrets
  namespace: usesend
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: usesend-app-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: nextauth-secret
    remoteRef:
      key: usesend-app
      property: nextauth-secret
  - secretKey: github-id
    remoteRef:
      key: usesend-app
      property: github-id
  - secretKey: github-secret
    remoteRef:
      key: usesend-app
      property: github-secret
  - secretKey: aws-access-key
    remoteRef:
      key: usesend-s3
      property: access-key
  - secretKey: aws-secret-key
    remoteRef:
      key: usesend-s3
      property: secret-key
  - secretKey: aws-region
    remoteRef:
      key: usesend-s3
      property: region
  - secretKey: aws-endpoint
    remoteRef:
      key: usesend-s3
      property: endpoint
  - secretKey: aws-bucket
    remoteRef:
      key: usesend-s3
      property: bucket
