apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: usesend-db-credentials
  namespace: usesend
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: usesend-db-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: username
    remoteRef:
      key: usesend-db
      property: username
  - secretKey: password
    remoteRef:
      key: usesend-db
      property: password
