apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: usesend-redis-secret
  namespace: usesend
spec:
  refreshInterval: 1h
  refreshPolicy: Periodic
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: usesend-redis-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: password
    remoteRef:
      key: usesend-redis
      property: password
