---
apiVersion: v1
kind: Namespace
metadata:
  name: nofx
  labels:
    app.kubernetes.io/name: nofx
    app.kubernetes.io/instance: nofx
    app.kubernetes.io/part-of: nofx
    nokiy.net/cluster-secret-store: "production"
