apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-postgres-credentials
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: synapse-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: synapse
        property: SYNAPSE_POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: synapse
        property: SYNAPSE_POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mas-postgres-credentials
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: mas-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: synapse
        property: MAS_POSTGRES_USERNAME
    - secretKey: password
      remoteRef:
        key: mas-postgres
        property: MAS_POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-config
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: synapse-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        homeserver.yaml: "{{ .homeserver_yaml }}"
        signing.key: "{{ .signing_key }}"
  data:
    - secretKey: homeserver_yaml
      remoteRef:
        key: synapse-config
        property: homeserver_yaml
    - secretKey: signing_key
      remoteRef:
        key: synapse-config
        property: signing_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mas-config
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: mas-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: mas-config
