apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-postgres-credentials
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: synapse-postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        username: synapse
        password: "{{ .POSTGRES_PASSWORD }}"
        synapse-user: synapse
        synapse-password: "{{ .POSTGRES_PASSWORD }}"
        mas-user: mas
        mas-password: "{{ .POSTGRES_PASSWORD }}"
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: synapse
        property: POSTGRES_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synapse-config
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: synapse-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        homeserver.yaml: "{{ .homeserver_yaml }}"
        signing.key: "{{ .signing_key }}"
  data:
    - secretKey: homeserver_yaml
      remoteRef:
        key: synapse-config
        property: homeserver_yaml
    - secretKey: signing_key
      remoteRef:
        key: synapse-config
        property: signing_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mas-config
  namespace: synapse
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: mas-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: mas-config
