apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: huggingface-daily-papers-secrets
  namespace: tg-bot
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: huggingface-daily-papers-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: huggingface-daily-papers
          app.kubernetes.io/part-of: huggingface-daily-papers
      data:
        DATA_DIR: /data/daily
        ARCHIVE_DIR: /data/archive
        CHECK_INTERVAL: 3600

  data:
    - secretKey: TELEGRAM_CHANNEL_ID
      remoteRef:
        key: huggingface-daily-papers-tg-bot
        property: CHANNEL_ID
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: huggingface-daily-papers-tg-bot
        property: BOT_TOKEN
