apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: huggingface-daily-papers-secrets
  namespace: tg-bot
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: huggingface-daily-papers-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: huggingface-daily-papers
          app.kubernetes.io/part-of: huggingface-daily-papers
      data:
        DATA_DIR: /data/daily
        ARCHIVE_DIR: /data/archive
        CHECK_INTERVAL: "3600"
        TELEGRAM_CHANNEL_ID: "{{ .channel_id | quote }}"
        TELEGRAM_BOT_TOKEN: "{{ .bot_token | quote }}"
        ENABLE_AI_TRANSLATION: "true"
        TRANSLATION_TARGET_LANG: "simplified chinese"
        OPENAI_API_KEY: "{{ .openrouter_api_key | quote }}"
        OPENAI_BASE_URL: "{{ .openrouter_base_url | quote }}"
        OPENAI_MODEL: "openai/gpt-5-mini"

  data:
    - secretKey: channel_id
      remoteRef:
        key: huggingface-daily-papers-tg-bot
        property: CHANNEL_ID
    - secretKey: bot_token
      remoteRef:
        key: huggingface-daily-papers-tg-bot
        property: BOT_TOKEN
    - secretKey: openrouter_api_key
      remoteRef:
        key: openrouter
        property: API_KEY
    - secretKey: openrouter_base_url
      remoteRef:
        key: openrouter
        property: BASE_URL
