apiVersion: operator.victoriametrics.com/v1
kind: VLCluster
metadata:
  name: vl
  namespace: vm
spec:
  retentionPeriod: "30d"

  vlinsert:
    replicaCount: 1
  vlselect:
    replicaCount: 1
  vlstorage:
    replicaCount: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
