apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vm
  namespace: vm
spec:
  retentionPeriod: "30d"
  replicationFactor: 1

  vminsert:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vmstorage:
    replicaCount: 1
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
