apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: grafana-ro
  namespace: vm
  labels:
    vmauth: main
spec:
  # 建议让 operator 生成密码/Token（Secret 里拿）
  generatePassword: true

  targetRefs:
    # metrics 读：vmselect
    - crd:
        kind: VMCluster/vmselect
        name: vm
        namespace: vm
      target_path_suffix: "/select/0/prometheus"
      paths:
        - "/"
    # logs 读：vlselect（LogsQL）
    - crd:
        kind: VLCluster/vlselect
        name: vl
        namespace: vm
      target_path_suffix: "/select/0/logsql"
      paths:
        - "/"
