apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth-secrets
  namespace: tinyauth
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: tinyauth-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: tinyauth
        property: SECRET_KEY
