apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: omnigent-secrets
  namespace: omnigent
spec:
  refreshPolicy: Periodic
  refreshInterval: "1h"
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: omnigent-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      engineVersion: v2
      data:
        DATABASE_URL: 'postgresql+psycopg://omnigent:{{ .postgresPassword | urlquery | replace "+" "%20" }}@pooler-rw.postgres.svc.cluster.local:5432/omnigent'
        OMNIGENT_OIDC_CLIENT_ID: "{{ .oidcClientId }}"
        OMNIGENT_OIDC_CLIENT_SECRET: "{{ .oidcClientSecret }}"
        OMNIGENT_OIDC_COOKIE_SECRET: "{{ .oidcCookieSecret }}"
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: omnigent
        property: POSTGRES_PASSWORD
    - secretKey: oidcClientId
      remoteRef:
        key: omnigent
        property: OIDC_CLIENT_ID
    - secretKey: oidcClientSecret
      remoteRef:
        key: omnigent
        property: OIDC_CLIENT_SECRET
    - secretKey: oidcCookieSecret
      remoteRef:
        key: omnigent
        property: OIDC_COOKIE_SECRET
