---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mitra
  namespace: mitra
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "200"
  bootstrap:
    initdb:
      database: mitra
      owner: mitra
  storage:
    size: 10Gi
