---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mitra-config
  namespace: mitra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  target:
    name: mitra-config
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.yaml: |
          # Mitra configuration file

          # Database configuration
          # Characters `@` in password `/` in hostname should be percent-encoded
          database_url: postgres://mitra:{{ .db_password }}@cnpg-mitra:5432/mitra
          database_tls_ca_cert_path: /etc/mitra/database.pem

          # Directory where media attachments and temporary files are stored
          storage_dir: /var/lib/mitra
          # Directory where static files for web client (frontend) are stored
          web_client_dir: /usr/share/mitra/www
          # Directory where static files for web client customization are stored
          # Files in that directory will be served instead of files in `web_client_dir`
          # when their names match
          web_client_theme_dir: /var/lib/mitra/theme

          # Host and port where HTTP server accepts connections
          http_host: '0.0.0.0'
          http_port: 8383

          # Log level (debug, info, warn)
          log_level: info

          # Base URL
          instance_url: https://mitra.nokiy.net

          instance_title: Mitra Instance
          instance_short_description: A federated social network
          instance_description: |
            # Mitra
            Welcome to our Mitra instance!

          # Make list of instance admins public
          instance_staff_public: true
          # Make instance (local) timeline public
          instance_timeline_public: false

          registration:
            # Possible values: open, invite
            type: invite
            # Possible values: user, read_only_user
            default_role: user

          # Access token expiration time (seconds). Default: 604800 (7 days)
          authentication:
            token_expiration_time: 604800

          # Limits
          limits:
            media:
              file_size_limit: 20M
              profile_image_size_limit: 5M
              emoji_size_limit: 500K
            posts:
              character_limit: 5000
              attachment_limit: 16
              attachment_local_limit: 16

          # Data retention parameters
          # Objects will be deleted after the specified number of days
          data_retention:
            extraneous_posts: 15
            empty_profiles: 30

          # Federation parameters
          federation:
            enabled: true
            ssrf_protection_enabled: true
  data:
    - secretKey: db_password
      remoteRef:
        key: mitra
        property: POSTGRES_PASSWORD
