apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: production
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        yuzu.nokiy.net: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
  conditions:
    - namespaceSelector:
        matchLabels:
          nokiy.net/cluster-secret-store: "production"
