apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pds-secrets
  namespace: pds
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: pds-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: pds
        property: JWT_SECRET
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: pds
        property: ADMIN_PASSWORD
    - secretKey: PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
      remoteRef:
        key: pds
        property: PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
    - secretKey: EMAIL_SMTP_URL
      remoteRef:
        key: pds
        property: EMAIL_SMTP_URL
