apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-secrets
  namespace: hetzner
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: hetzner-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: hetzner
        property: TOKEN
    - secretKey: encryption-passphrase
      remoteRef:
        key: hetzner
        property: VOLUME_ENCRYPTION_KEY
