apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id
commonLabels:
  app.kubernetes.io/name: pocket-id
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
