apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: pocket-id-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: pocket-id
        property: ENCRYPTION_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litestream-secrets
  namespace: pocket-id
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: litestream-secrets
    template:
      engineVersion: v2
      data:
        litestream.yml: |
          access-key-id: {{ .aws_access_key_id | quote }}
          secret-access-key: {{ .aws_secret_access_key | quote }}

          dbs:
            - path: /data/pocket-id.db
              replicas:
                - type: s3
                  bucket: backup
                  path: pocket-id-litestream
                  endpoint: https://nokiy.net
                  force-path-style: false
                  age:
                    identities:
                      - {{ .AGE_SECRET_KEY }}
                    recipients:
                      - {{ .AGE_PUBLIC_KEY }}

  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: backup.nokiy.net
        property: ACCESS_KEY
    - secretKey: aws_secret_access_key
      remoteRef:
        key: backup.nokiy.net
        property: SECRET_KEY
    - secretKey: AGE_SECRET_KEY
      remoteRef:
        key: litestream
        property: AGE_SECRET_KEY
    - secretKey: AGE_PUBLIC_KEY
      remoteRef:
        key: litestream
        property: AGE_PUBLIC_KEY
