---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blog-ghcr-pull-secret
  namespace: blog
spec:
  secretStoreRef:
    name: production
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h"
  target:
    name: blog-ghcr-pull-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"{{ printf "%s:%s" .username .token | b64enc }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: ghcr-pull-secret
        property: username
    - secretKey: token
      remoteRef:
        key: ghcr-pull-secret
        property: token
